config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :babies
  get 'home/about'
  #root 'home#index'
  root 'babies#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    belongs_to  :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         has_many :babies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /babies or /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1 or /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
    @friend = current_user.babies.build
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies or /babies.json
  def create
    #@baby = Baby.new(baby_params)
    @baby = current_user.babies.build(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to baby_url(@baby), notice: "Baby was successfully created." }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1 or /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to baby_url(@baby), notice: "Baby was successfully updated." }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1 or /babies/1.json
  def destroy
    @baby.destroy

    respond_to do |format|
      format.html { redirect_to babies_url, notice: "Baby was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def correct_user
    @baby = current_user.babies.find_by(id: params[:id])
    redirect_to babies_path, notice: "Cant Edit the Baby" if @baby.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:first_name, :last_name, :gender, :client_email, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
        <% baby.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, 
    class:"form-control", placeholder: "First Name" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :last_name, 
    class:"form-control", placeholder: "Last Name" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :gender, 
    class:"form-control",placeholder: "Gender" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :client_email,
     class:"form-control", placeholder: "Client Email" %>
  </div>
  
  <div class="field form-group">
   
    <%= form.number_field :user_id,id: :baby_user_id,
     class:"form-control", value: current_user.id,type: :hidden %>
  </div>
  
    
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby,class: "btn btn-primary" %> |

<%= link_to 'Back', babies_path, class: "btn btn-primary"%>|

<%= link_to 'Delete', @baby, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>

app/views/babies/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">

  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Client email</th>
      <th>User Id</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
    <% if baby.user == current_user %>
      <tr>
        <td>
        <%= link_to baby.first_name + ' ' + baby.last_name, baby %>
          
        </td>
        <td><%= baby.gender %></td>
        <td><%= baby.client_email %></td>
        <td><%= baby.user_id %></td>
        
        
        
        <td><%= link_to 'Delete', baby, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-outline-danger" %></td>
        
       
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path, class: "btn btn-success"%>

<%else%>
<h1>Baby Names App</h1>
<p>Home of Your Baby Names</p>

<%end%>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<br/>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  <%= @baby.first_name %>
  <%= @baby.last_name %>
  </h1>
  <p class="lead">
  
    <%= @baby.gender %>|
    <%= @baby.client_email %>|
</p>

  <hr class="my-4">
  
  <%= link_to 'Edit', edit_baby_path(@baby),class:"btn btn-primary" %> |
  <%= link_to 'Back', babies_path,class:"btn btn-primary" %> |
  <%= link_to 'Delete', @baby, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Baby Names App', root_path, class:"navbar-brand" %>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
   
      
      
      <li class="nav-item">
       
        <%= link_to "Babies", babies_path, class: "nav-link" %>
      </li>
      
            
      
      <% if user_signed_in? %>
      <li class="nav-item">
       
        <%= link_to "Add Babies", new_baby_path, class: "nav-link" %>
      </li>
      
   
      
      
       <li class="nav-item">
       
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      
      <li class="nav-item">
       
        <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
      </li>
      
      
       <% else %>
      <li class="nav-item">
       
        <%= link_to "Join Us", new_user_registration_path, class: "nav-link" %>
      </li><li class="nav-item">
       
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
     <% end %>    
          
            
    </ul>
   
  </div>
</nav>

app/views/home/index.html.erb
<h1>Baby Names App</h1>
<p>Home of Your Baby Names</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Baby Names App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>
  <body>
  
  <%= render 'home/header' %>
  <div class="container">
  
  <% if Warning %>
  
  <%= render 'layouts/alerts' %>
  
  <%end%>
  <br/>
    <%= yield %>
   </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>